defaultPortal: Kevin
portals:
  - name: Kevin
    portalId: 21450339
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLaf65jyLxIJAA0AAAAA4A0DGOOcnQoghrGsBiju6QwyFOU9u_AA44prrc-AKUqKTSkBng8YOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhQrzsgcoW3dDNZo1gttaIfxA2QAHEoDbmExUgBaAA
        expiresAt: '2022-02-22T20:23:54.044Z'
    personalAccessKey: >-
      CiQ0NzMwNzM0OS1mOTlhLTRmNmYtYjk1MS03M2YzMDI0YTM2ZTEQ45ydChiGsawGKhkABeaRghK_hih__Ow79EqLfsulFU_Od03eSgNuYTE
