defaultPortal: Kevin
portals:
  - name: Kevin
    portalId: 21450339
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNyrmPLvLxIJAA0AAAAA4A0DGOOcnQoghrGsBiju6QwyFK9nunxjGkLipoUPvP-WctleNGTIOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSgwagajVh0HKv4wZJxsOpIoI4qrkoDbmExUgBaAA
        expiresAt: '2022-02-15T16:45:13.059Z'
    personalAccessKey: >-
      CiQ0NzMwNzM0OS1mOTlhLTRmNmYtYjk1MS03M2YzMDI0YTM2ZTEQ45ydChiGsawGKhkABeaRghK_hih__Ow79EqLfsulFU_Od03eSgNuYTE
