defaultPortal: Kevin
portals:
  - name: Kevin
    portalId: 21450339
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CL_F0ZnyLxIJAA0AAAAA4A0DGOOcnQoghrGsBiju6QwyFHUsfKnYOfoA2qIOCtn68PNK1g0YOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSAWiYAZAWkxm5YxfB024AlZ5rBtEoDbmExUgBaAA
        expiresAt: '2022-02-22T20:51:50.085Z'
    personalAccessKey: >-
      CiQ0NzMwNzM0OS1mOTlhLTRmNmYtYjk1MS03M2YzMDI0YTM2ZTEQ45ydChiGsawGKhkABeaRghK_hih__Ow79EqLfsulFU_Od03eSgNuYTE
